image: weltn24/up-docker-node-chrome-headless

cache:
  paths:
    - node_modules/

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - npm install
    - npm test
  artifacts:
    paths:
      - coverage/

deploy:
  stage: deploy
  environment:
    name: $CI_COMMIT_REF_NAME
  script:
    - npm install
    - npm run build
    - TARGET=$CI_COMMIT_REF_NAME AWS_BUCKET=cdn.clearroadlab.io npm run deploy
  only:
    - master
    - develop
