ruby '>=2.3.1'
source 'https://rubygems.org'

# Middleman
gem 'middleman', '~> 4.4.0'
gem 'middleman-syntax', '~> 3.0.0'
gem 'middleman-autoprefixer', '~> 2.7.1'
gem 'middleman-sprockets', '~> 4.1.1'
gem 'rouge', '~> 2.0.5'
gem 'redcarpet', '~> 3.4.0'
gem 'nokogiri', '~> 1.8.5'

gem 'rake'
gem 'font-awesome-sass', '~> 5.2.0'
